### ISSUE TITLE
-0.00000000

### ISSUE THREAD

**Issue by murpholinox** [Avogadro/avogadro.cc#1]
![captura de pantalla de 2017-12-14 13-25-27](https://user-images.githubusercontent.com/732802/34010490-879713f4-e0d2-11e7-9d03-9d1c5c583def.png)

**Comment by ghutchis** [comment]
Is this a question about Avogadro or about the website?

**Comment by murpholinox** [comment]
I think it is a minor bug, the Cartesian Editor shows the fractional coordinates with -0.000..... should be 0.000.....
right?

**Comment by ghutchis** [comment]
This repository is for the website, not the app.
